import {
  User,
  ClothingItem,
  Outfit,
  Post,
  Challenge,
  Notification,
  AffiliateItem,
  EarningsData,
  StyleDNA,
} from "@/types";

export const currentUser: User = {
  id: "user-1",
  email: "sarah@example.com",
  username: "sarahstyles",
  display_name: "Sarah Mitchell",
  avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
  bio: "Fashion enthusiast | NYC based | Mixing high & low since '19 ✨",
  website: "https://sarahstyles.com",
  instagram_handle: "@sarahstyles",
  style_dna: ["Minimalist Chic", "Street Luxe", "Coastal Cool"],
  badges: [
    { id: "b1", name: "Early Adopter", icon: "🌟", description: "Joined in beta", earned_at: "2024-01-15" },
    { id: "b2", name: "Style Icon", icon: "👑", description: "100+ outfit posts", earned_at: "2024-06-01" },
    { id: "b3", name: "Top Earner", icon: "💰", description: "Earned $1000+", earned_at: "2024-09-15" },
  ],
  subscription_tier: "influencer",
  stripe_customer_id: "cus_123",
  stripe_connect_id: "acct_123",
  commission_rate: 12,
  total_earnings: 3847.52,
  follower_count: 12400,
  following_count: 342,
  post_count: 156,
  closet_item_count: 234,
  created_at: "2024-01-15T00:00:00Z",
  updated_at: "2024-12-01T00:00:00Z",
};

export const mockUsers: User[] = [
  currentUser,
  {
    id: "user-2",
    email: "emma@example.com",
    username: "emmavogue",
    display_name: "Emma Chen",
    avatar_url: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200",
    bio: "Sustainable fashion advocate | LA vibes 🌿",
    website: "",
    instagram_handle: "@emmavogue",
    style_dna: ["Sustainable Chic", "Boho Luxe"],
    badges: [{ id: "b4", name: "Eco Warrior", icon: "🌿", description: "100% sustainable closet", earned_at: "2024-03-01" }],
    subscription_tier: "stylist",
    stripe_customer_id: "cus_456",
    stripe_connect_id: null,
    commission_rate: 5,
    total_earnings: 892.30,
    follower_count: 8900,
    following_count: 215,
    post_count: 89,
    closet_item_count: 167,
    created_at: "2024-02-20T00:00:00Z",
    updated_at: "2024-11-15T00:00:00Z",
  },
  {
    id: "user-3",
    email: "mia@example.com",
    username: "miafashion",
    display_name: "Mia Rodriguez",
    avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200",
    bio: "Streetwear queen 👟 Sneaker collector",
    website: "https://miafashion.co",
    instagram_handle: "@miafashion",
    style_dna: ["Streetwear", "Athleisure", "Y2K"],
    badges: [{ id: "b5", name: "Challenge Winner", icon: "🏆", description: "Won 3 challenges", earned_at: "2024-05-01" }],
    subscription_tier: "influencer",
    stripe_customer_id: "cus_789",
    stripe_connect_id: "acct_789",
    commission_rate: 12,
    total_earnings: 5621.80,
    follower_count: 24500,
    following_count: 178,
    post_count: 234,
    closet_item_count: 312,
    created_at: "2024-01-05T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
  },
  {
    id: "user-4",
    email: "olivia@example.com",
    username: "oliviastyle",
    display_name: "Olivia Park",
    avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200",
    bio: "Minimalist wardrobe | Capsule closet enthusiast",
    website: "",
    instagram_handle: "@oliviastyle",
    style_dna: ["Minimalist", "Scandinavian", "Classic"],
    badges: [],
    subscription_tier: "free",
    stripe_customer_id: null,
    stripe_connect_id: null,
    commission_rate: 0,
    total_earnings: 0,
    follower_count: 3200,
    following_count: 421,
    post_count: 45,
    closet_item_count: 48,
    created_at: "2024-06-10T00:00:00Z",
    updated_at: "2024-11-30T00:00:00Z",
  },
  {
    id: "user-5",
    email: "zoey@example.com",
    username: "zoeytrends",
    display_name: "Zoey Williams",
    avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200",
    bio: "Trend forecaster | Fashion editor | Coffee addict ☕",
    website: "https://zoeytrends.com",
    instagram_handle: "@zoeytrends",
    style_dna: ["Editorial", "Power Dressing", "Avant-Garde"],
    badges: [
      { id: "b6", name: "Verified", icon: "✅", description: "Verified influencer", earned_at: "2024-02-01" },
      { id: "b7", name: "Trendsetter", icon: "🔥", description: "10 trending posts", earned_at: "2024-07-15" },
    ],
    subscription_tier: "influencer",
    stripe_customer_id: "cus_012",
    stripe_connect_id: "acct_012",
    commission_rate: 12,
    total_earnings: 12340.90,
    follower_count: 67800,
    following_count: 128,
    post_count: 423,
    closet_item_count: 567,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-12-01T00:00:00Z",
  },
];

export const mockClothingItems: ClothingItem[] = [
  {
    id: "item-1",
    user_id: "user-1",
    image_url: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400",
    thumbnail_url: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=200",
    category: "tops",
    subcategory: "blouse",
    brand: "Zara",
    color: ["white", "cream"],
    pattern: "solid",
    material: "silk",
    season: ["spring", "summer", "fall"],
    occasion: ["work", "casual", "date_night"],
    style_tags: ["elegant", "classic", "versatile"],
    purchase_url: "https://zara.com/blouse-123",
    affiliate_url: "https://affiliate.link/zara-blouse-123",
    price: 49.90,
    ai_description: "Cream silk blouse with relaxed fit, perfect for layering or wearing alone",
    is_favorite: true,
    wear_count: 24,
    last_worn: "2024-11-28",
    created_at: "2024-03-15T00:00:00Z",
  },
  {
    id: "item-2",
    user_id: "user-1",
    image_url: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400",
    thumbnail_url: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=200",
    category: "bottoms",
    subcategory: "jeans",
    brand: "Levi's",
    color: ["blue", "indigo"],
    pattern: "solid",
    material: "denim",
    season: ["all"],
    occasion: ["casual", "everyday"],
    style_tags: ["classic", "staple", "high-waisted"],
    purchase_url: "https://levis.com/501-jeans",
    affiliate_url: "https://affiliate.link/levis-501",
    price: 98.00,
    ai_description: "Classic high-waisted straight-leg jeans in medium indigo wash",
    is_favorite: true,
    wear_count: 45,
    last_worn: "2024-12-01",
    created_at: "2024-02-10T00:00:00Z",
  },
  {
    id: "item-3",
    user_id: "user-1",
    image_url: "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d44?w=400",
    thumbnail_url: "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d44?w=200",
    category: "dresses",
    subcategory: "midi dress",
    brand: "Reformation",
    color: ["green", "sage"],
    pattern: "floral",
    material: "viscose",
    season: ["spring", "summer"],
    occasion: ["date_night", "party", "casual"],
    style_tags: ["romantic", "flowy", "feminine"],
    purchase_url: "https://reformation.com/dress-456",
    affiliate_url: "https://affiliate.link/reformation-dress",
    price: 218.00,
    ai_description: "Sage green floral midi dress with puff sleeves and smocked bodice",
    is_favorite: false,
    wear_count: 8,
    last_worn: "2024-09-15",
    created_at: "2024-04-20T00:00:00Z",
  },
  {
    id: "item-4",
    user_id: "user-1",
    image_url: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400",
    thumbnail_url: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=200",
    category: "outerwear",
    subcategory: "leather jacket",
    brand: "AllSaints",
    color: ["black"],
    pattern: "solid",
    material: "leather",
    season: ["fall", "winter", "spring"],
    occasion: ["casual", "date_night", "party"],
    style_tags: ["edgy", "cool", "statement"],
    purchase_url: "https://allsaints.com/jacket-789",
    affiliate_url: "https://affiliate.link/allsaints-jacket",
    price: 498.00,
    ai_description: "Classic black leather biker jacket with silver hardware",
    is_favorite: true,
    wear_count: 32,
    last_worn: "2024-11-30",
    created_at: "2024-01-20T00:00:00Z",
  },
  {
    id: "item-5",
    user_id: "user-1",
    image_url: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400",
    thumbnail_url: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=200",
    category: "shoes",
    subcategory: "sneakers",
    brand: "Nike",
    color: ["white"],
    pattern: "solid",
    material: "leather",
    season: ["all"],
    occasion: ["casual", "everyday", "athletic"],
    style_tags: ["classic", "clean", "versatile"],
    purchase_url: "https://nike.com/af1",
    affiliate_url: "https://affiliate.link/nike-af1",
    price: 110.00,
    ai_description: "White Nike Air Force 1 Low sneakers",
    is_favorite: true,
    wear_count: 67,
    last_worn: "2024-12-01",
    created_at: "2024-01-05T00:00:00Z",
  },
  {
    id: "item-6",
    user_id: "user-1",
    image_url: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400",
    thumbnail_url: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=200",
    category: "bags",
    subcategory: "crossbody",
    brand: "Bottega Veneta",
    color: ["brown", "caramel"],
    pattern: "woven",
    material: "leather",
    season: ["all"],
    occasion: ["casual", "work", "date_night"],
    style_tags: ["luxury", "iconic", "investment"],
    purchase_url: "https://bottegaveneta.com/cassette",
    affiliate_url: "https://affiliate.link/bv-cassette",
    price: 2950.00,
    ai_description: "Bottega Veneta Cassette bag in caramel intrecciato leather",
    is_favorite: true,
    wear_count: 41,
    last_worn: "2024-11-29",
    created_at: "2024-02-14T00:00:00Z",
  },
  {
    id: "item-7",
    user_id: "user-1",
    image_url: "https://images.unsplash.com/photo-1434389677669-e08b4cda3f78?w=400",
    thumbnail_url: "https://images.unsplash.com/photo-1434389677669-e08b4cda3f78?w=200",
    category: "tops",
    subcategory: "sweater",
    brand: "COS",
    color: ["beige", "oatmeal"],
    pattern: "solid",
    material: "cashmere",
    season: ["fall", "winter"],
    occasion: ["casual", "work", "everyday"],
    style_tags: ["cozy", "minimalist", "luxe"],
    purchase_url: "https://cos.com/cashmere-sweater",
    affiliate_url: "https://affiliate.link/cos-sweater",
    price: 175.00,
    ai_description: "Oatmeal cashmere crew-neck sweater with relaxed fit",
    is_favorite: false,
    wear_count: 18,
    last_worn: "2024-11-25",
    created_at: "2024-09-01T00:00:00Z",
  },
  {
    id: "item-8",
    user_id: "user-1",
    image_url: "https://images.unsplash.com/photo-1603252109303-2751441dd157?w=400",
    thumbnail_url: "https://images.unsplash.com/photo-1603252109303-2751441dd157?w=200",
    category: "accessories",
    subcategory: "sunglasses",
    brand: "Ray-Ban",
    color: ["black", "gold"],
    pattern: "solid",
    material: "metal",
    season: ["spring", "summer"],
    occasion: ["casual", "vacation", "everyday"],
    style_tags: ["classic", "timeless", "cool"],
    purchase_url: "https://ray-ban.com/aviator",
    affiliate_url: "https://affiliate.link/rayban-aviator",
    price: 163.00,
    ai_description: "Ray-Ban Aviator Classic sunglasses with gold frame",
    is_favorite: false,
    wear_count: 30,
    last_worn: "2024-08-20",
    created_at: "2024-05-15T00:00:00Z",
  },
  {
    id: "item-9",
    user_id: "user-1",
    image_url: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400",
    thumbnail_url: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=200",
    category: "dresses",
    subcategory: "evening gown",
    brand: "Self-Portrait",
    color: ["black"],
    pattern: "lace",
    material: "polyester blend",
    season: ["all"],
    occasion: ["formal", "party", "date_night"],
    style_tags: ["glamorous", "sophisticated", "statement"],
    purchase_url: "https://self-portrait.com/lace-gown",
    affiliate_url: "https://affiliate.link/sp-gown",
    price: 475.00,
    ai_description: "Black lace midi dress with high neckline and sheer panels",
    is_favorite: true,
    wear_count: 4,
    last_worn: "2024-10-31",
    created_at: "2024-07-20T00:00:00Z",
  },
  {
    id: "item-10",
    user_id: "user-1",
    image_url: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400",
    thumbnail_url: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=200",
    category: "outerwear",
    subcategory: "trench coat",
    brand: "Burberry",
    color: ["beige", "tan"],
    pattern: "solid",
    material: "cotton gabardine",
    season: ["spring", "fall"],
    occasion: ["work", "casual", "formal"],
    style_tags: ["classic", "timeless", "investment", "british"],
    purchase_url: "https://burberry.com/trench",
    affiliate_url: "https://affiliate.link/burberry-trench",
    price: 2290.00,
    ai_description: "Classic Burberry trench coat in honey beige with check lining",
    is_favorite: true,
    wear_count: 22,
    last_worn: "2024-11-20",
    created_at: "2024-03-01T00:00:00Z",
  },
  {
    id: "item-11",
    user_id: "user-1",
    image_url: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400",
    thumbnail_url: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=200",
    category: "tops",
    subcategory: "t-shirt",
    brand: "Everlane",
    color: ["black"],
    pattern: "solid",
    material: "cotton",
    season: ["all"],
    occasion: ["casual", "everyday"],
    style_tags: ["basic", "essential", "sustainable"],
    purchase_url: "https://everlane.com/organic-tee",
    affiliate_url: "https://affiliate.link/everlane-tee",
    price: 30.00,
    ai_description: "Black organic cotton crew neck t-shirt, essential wardrobe staple",
    is_favorite: false,
    wear_count: 52,
    last_worn: "2024-12-01",
    created_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "item-12",
    user_id: "user-1",
    image_url: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400",
    thumbnail_url: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=200",
    category: "shoes",
    subcategory: "heels",
    brand: "Jimmy Choo",
    color: ["nude", "beige"],
    pattern: "solid",
    material: "patent leather",
    season: ["all"],
    occasion: ["formal", "date_night", "work"],
    style_tags: ["elegant", "classic", "luxury"],
    purchase_url: "https://jimmychoo.com/anouk",
    affiliate_url: "https://affiliate.link/jc-anouk",
    price: 650.00,
    ai_description: "Nude patent leather pointed-toe pumps, 100mm heel",
    is_favorite: true,
    wear_count: 15,
    last_worn: "2024-11-15",
    created_at: "2024-04-01T00:00:00Z",
  },
];

const affiliateItems: AffiliateItem[] = [
  { id: "aff-1", name: "Silk Blouse", brand: "Zara", price: 49.90, image_url: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=200", affiliate_url: "https://affiliate.link/zara-blouse-123", commission_rate: 5 },
  { id: "aff-2", name: "501 Jeans", brand: "Levi's", price: 98.00, image_url: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=200", affiliate_url: "https://affiliate.link/levis-501", commission_rate: 5 },
  { id: "aff-3", name: "Leather Jacket", brand: "AllSaints", price: 498.00, image_url: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=200", affiliate_url: "https://affiliate.link/allsaints-jacket", commission_rate: 8 },
  { id: "aff-4", name: "Air Force 1", brand: "Nike", price: 110.00, image_url: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=200", affiliate_url: "https://affiliate.link/nike-af1", commission_rate: 4 },
];

export const mockOutfits: Outfit[] = [
  {
    id: "outfit-1",
    user_id: "user-1",
    name: "Casual Friday Chic",
    description: "Perfect blend of relaxed and polished for a casual workday",
    items: [mockClothingItems[0], mockClothingItems[1], mockClothingItems[4], mockClothingItems[5]],
    item_ids: ["item-1", "item-2", "item-5", "item-6"],
    occasion: "work",
    season: "fall",
    weather: "Partly cloudy, 65°F",
    ai_generated: true,
    ai_visualization_url: "https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?w=600",
    flat_lay_url: null,
    style_score: 92,
    is_favorite: true,
    created_at: "2024-11-28T10:00:00Z",
  },
  {
    id: "outfit-2",
    user_id: "user-1",
    name: "Date Night Glam",
    description: "Sophisticated and alluring for a special evening",
    items: [mockClothingItems[8], mockClothingItems[11], mockClothingItems[5]],
    item_ids: ["item-9", "item-12", "item-6"],
    occasion: "date_night",
    season: "all",
    weather: "Clear skies, 55°F",
    ai_generated: true,
    ai_visualization_url: "https://images.unsplash.com/photo-1502716119720-b23a1e3f2516?w=600",
    flat_lay_url: null,
    style_score: 96,
    is_favorite: true,
    created_at: "2024-11-25T18:00:00Z",
  },
  {
    id: "outfit-3",
    user_id: "user-1",
    name: "Weekend Brunch",
    description: "Effortlessly stylish for weekend outings",
    items: [mockClothingItems[6], mockClothingItems[1], mockClothingItems[4], mockClothingItems[7]],
    item_ids: ["item-7", "item-2", "item-5", "item-8"],
    occasion: "casual",
    season: "fall",
    weather: "Sunny, 58°F",
    ai_generated: false,
    ai_visualization_url: null,
    flat_lay_url: null,
    style_score: 88,
    is_favorite: false,
    created_at: "2024-11-20T09:00:00Z",
  },
];

export const mockPosts: Post[] = [
  {
    id: "post-1",
    user_id: "user-1",
    user: currentUser,
    outfit_id: "outfit-1",
    outfit: mockOutfits[0],
    image_url: "https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?w=600",
    caption: "Casual Friday done right! This silk blouse + vintage jeans combo is my go-to. Link to shop in bio 🛍️ #OOTD #CasualChic",
    tags: ["ootd", "casualchic", "fridayvibes", "workwear"],
    has_affiliate_links: true,
    affiliate_items: affiliateItems.slice(0, 2),
    like_count: 342,
    comment_count: 28,
    save_count: 156,
    share_count: 12,
    is_liked: false,
    is_saved: false,
    challenge_id: null,
    created_at: "2024-11-28T14:30:00Z",
  },
  {
    id: "post-2",
    user_id: "user-3",
    user: mockUsers[2],
    outfit_id: null,
    outfit: null,
    image_url: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600",
    caption: "Streetwear season is here! Layering game strong with this oversized blazer and chunky sneakers combo 🔥 #StreetStyle #FallFashion",
    tags: ["streetstyle", "fallfashion", "sneakerhead", "layering"],
    has_affiliate_links: true,
    affiliate_items: [affiliateItems[2], affiliateItems[3]],
    like_count: 891,
    comment_count: 67,
    save_count: 423,
    share_count: 45,
    is_liked: true,
    is_saved: true,
    challenge_id: null,
    created_at: "2024-11-27T16:45:00Z",
  },
  {
    id: "post-3",
    user_id: "user-2",
    user: mockUsers[1],
    outfit_id: null,
    outfit: null,
    image_url: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600",
    caption: "Sustainable fashion doesn't have to be boring! This thrifted maxi dress is giving everything 🌿✨ #SustainableFashion #ThriftFlip",
    tags: ["sustainablefashion", "thriftflip", "ecofashion", "vintagestyle"],
    has_affiliate_links: false,
    affiliate_items: [],
    like_count: 567,
    comment_count: 43,
    save_count: 289,
    share_count: 23,
    is_liked: false,
    is_saved: true,
    challenge_id: null,
    created_at: "2024-11-26T11:20:00Z",
  },
  {
    id: "post-4",
    user_id: "user-5",
    user: mockUsers[4],
    outfit_id: null,
    outfit: null,
    image_url: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=600",
    caption: "Power dressing for the boardroom. This tailored suit makes me feel unstoppable 💼 Head-to-toe details in the comments! #PowerDressing #BossLady",
    tags: ["powerdressing", "bosslady", "suitup", "workwear"],
    has_affiliate_links: true,
    affiliate_items: affiliateItems,
    like_count: 1234,
    comment_count: 89,
    save_count: 678,
    share_count: 67,
    is_liked: true,
    is_saved: false,
    challenge_id: null,
    created_at: "2024-11-25T09:00:00Z",
  },
  {
    id: "post-5",
    user_id: "user-4",
    user: mockUsers[3],
    outfit_id: null,
    outfit: null,
    image_url: "https://images.unsplash.com/photo-1485968579580-b6d095142e6e?w=600",
    caption: "Capsule wardrobe update: These 5 pieces create 15+ outfits! Minimalism at its finest 🤍 #CapsuleWardrobe #Minimalist",
    tags: ["capsulewardrobe", "minimalist", "lessismore", "wardrobebasics"],
    has_affiliate_links: false,
    affiliate_items: [],
    like_count: 445,
    comment_count: 56,
    save_count: 890,
    share_count: 34,
    is_liked: false,
    is_saved: false,
    challenge_id: null,
    created_at: "2024-11-24T15:30:00Z",
  },
  {
    id: "post-6",
    user_id: "user-1",
    user: currentUser,
    outfit_id: "outfit-2",
    outfit: mockOutfits[1],
    image_url: "https://images.unsplash.com/photo-1502716119720-b23a1e3f2516?w=600",
    caption: "Date night ready! This lace dress never fails to make me feel confident ✨ #DateNight #GlamStyle",
    tags: ["datenight", "glamstyle", "eveningwear", "lacedress"],
    has_affiliate_links: true,
    affiliate_items: affiliateItems.slice(0, 1),
    like_count: 678,
    comment_count: 45,
    save_count: 312,
    share_count: 19,
    is_liked: false,
    is_saved: false,
    challenge_id: null,
    created_at: "2024-11-23T19:00:00Z",
  },
  {
    id: "post-7",
    user_id: "user-3",
    user: mockUsers[2],
    outfit_id: null,
    outfit: null,
    image_url: "https://images.unsplash.com/photo-1475180098004-ca77a66827be?w=600",
    caption: "Festival season may be over but this look lives rent-free in my head 🎪 #FestivalFashion #BohoVibes",
    tags: ["festivalfashion", "bohovibes", "coachella", "freespirit"],
    has_affiliate_links: false,
    affiliate_items: [],
    like_count: 923,
    comment_count: 71,
    save_count: 445,
    share_count: 38,
    is_liked: true,
    is_saved: false,
    challenge_id: null,
    created_at: "2024-11-22T12:00:00Z",
  },
  {
    id: "post-8",
    user_id: "user-5",
    user: mockUsers[4],
    outfit_id: null,
    outfit: null,
    image_url: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600",
    caption: "Monochrome moment: All-white everything for a fresh winter look ❄️ #Monochrome #WinterWhite #Editorial",
    tags: ["monochrome", "winterwhite", "editorial", "fashionforward"],
    has_affiliate_links: true,
    affiliate_items: affiliateItems.slice(2),
    like_count: 1567,
    comment_count: 102,
    save_count: 789,
    share_count: 89,
    is_liked: false,
    is_saved: true,
    challenge_id: null,
    created_at: "2024-11-21T10:15:00Z",
  },
];

export const mockChallenges: Challenge[] = [
  {
    id: "challenge-1",
    title: "Winter Wonderland",
    description: "Show us your best winter outfit! Layer up in style and share your coziest cold-weather looks.",
    theme: "winter",
    cover_image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600",
    start_date: "2024-12-01T00:00:00Z",
    end_date: "2024-12-15T23:59:59Z",
    prize_description: "$500 shopping spree + Featured profile for 1 month",
    entry_count: 234,
    vote_count: 4521,
    status: "active",
    winner_id: null,
    winner: null,
    created_at: "2024-11-28T00:00:00Z",
  },
  {
    id: "challenge-2",
    title: "Thrift Flip Challenge",
    description: "Transform a thrift store find into a runway-worthy outfit. Creativity is key!",
    theme: "sustainable",
    cover_image: "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=600",
    start_date: "2024-12-15T00:00:00Z",
    end_date: "2024-12-31T23:59:59Z",
    prize_description: "$250 thrift store gift card + Eco Warrior badge",
    entry_count: 0,
    vote_count: 0,
    status: "upcoming",
    winner_id: null,
    winner: null,
    created_at: "2024-11-30T00:00:00Z",
  },
  {
    id: "challenge-3",
    title: "Color Block Master",
    description: "Mix and match bold colors to create eye-catching color-blocked outfits!",
    theme: "colorful",
    cover_image: "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=600",
    start_date: "2024-11-15T00:00:00Z",
    end_date: "2024-11-30T23:59:59Z",
    prize_description: "$300 fashion credit + Trendsetter badge",
    entry_count: 567,
    vote_count: 12340,
    status: "voting",
    winner_id: null,
    winner: null,
    created_at: "2024-11-10T00:00:00Z",
  },
  {
    id: "challenge-4",
    title: "90s Revival",
    description: "Channel your favorite 90s fashion moments! From grunge to glam, show us your retro style.",
    theme: "retro",
    cover_image: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=600",
    start_date: "2024-11-01T00:00:00Z",
    end_date: "2024-11-14T23:59:59Z",
    prize_description: "$200 vintage store credit",
    entry_count: 890,
    vote_count: 23456,
    status: "completed",
    winner_id: "user-3",
    winner: mockUsers[2],
    created_at: "2024-10-25T00:00:00Z",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    user_id: "user-1",
    type: "like",
    title: "New Like",
    message: "Emma Chen liked your post",
    image_url: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100",
    link: "/feed",
    is_read: false,
    actor_id: "user-2",
    actor: mockUsers[1],
    created_at: "2024-12-01T10:30:00Z",
  },
  {
    id: "notif-2",
    user_id: "user-1",
    type: "follow",
    title: "New Follower",
    message: "Zoey Williams started following you",
    image_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100",
    link: "/profile/zoeytrends",
    is_read: false,
    actor_id: "user-5",
    actor: mockUsers[4],
    created_at: "2024-12-01T09:15:00Z",
  },
  {
    id: "notif-3",
    user_id: "user-1",
    type: "comment",
    title: "New Comment",
    message: "Mia Rodriguez commented: \"Love this outfit! 😍\"",
    image_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100",
    link: "/feed",
    is_read: false,
    actor_id: "user-3",
    actor: mockUsers[2],
    created_at: "2024-12-01T08:45:00Z",
  },
  {
    id: "notif-4",
    user_id: "user-1",
    type: "affiliate_click",
    title: "Affiliate Click!",
    message: "Someone clicked your Zara Silk Blouse link - $2.50 earned!",
    image_url: "",
    link: "/earnings",
    is_read: true,
    actor_id: "",
    actor: null,
    created_at: "2024-11-30T22:00:00Z",
  },
  {
    id: "notif-5",
    user_id: "user-1",
    type: "challenge",
    title: "Challenge Starting",
    message: "Winter Wonderland challenge is now live! Enter now 🏆",
    image_url: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=100",
    link: "/challenges",
    is_read: true,
    actor_id: "",
    actor: null,
    created_at: "2024-12-01T00:00:00Z",
  },
  {
    id: "notif-6",
    user_id: "user-1",
    type: "payout",
    title: "Payout Processed",
    message: "Your November payout of $347.52 has been sent to your bank!",
    image_url: "",
    link: "/earnings",
    is_read: true,
    actor_id: "",
    actor: null,
    created_at: "2024-11-30T12:00:00Z",
  },
  {
    id: "notif-7",
    user_id: "user-1",
    type: "badge",
    title: "New Badge Earned!",
    message: "You earned the Top Earner badge! 💰",
    image_url: "",
    link: "/profile/sarahstyles",
    is_read: true,
    actor_id: "",
    actor: null,
    created_at: "2024-11-29T15:00:00Z",
  },
];

export const mockEarnings: EarningsData = {
  total_earnings: 3847.52,
  pending_earnings: 423.18,
  this_month: 423.18,
  last_month: 347.52,
  total_clicks: 12450,
  total_conversions: 892,
  conversion_rate: 7.2,
  daily_earnings: [
    { date: "2024-11-25", amount: 42.30, clicks: 156 },
    { date: "2024-11-26", amount: 38.90, clicks: 134 },
    { date: "2024-11-27", amount: 67.20, clicks: 245 },
    { date: "2024-11-28", amount: 55.40, clicks: 198 },
    { date: "2024-11-29", amount: 71.80, clicks: 267 },
    { date: "2024-11-30", amount: 48.60, clicks: 178 },
    { date: "2024-12-01", amount: 98.98, clicks: 312 },
  ],
  top_items: [
    { item: affiliateItems[2], clicks: 3456, conversions: 234, revenue: 1247.50 },
    { item: affiliateItems[0], clicks: 2890, conversions: 198, revenue: 892.30 },
    { item: affiliateItems[3], clicks: 2100, conversions: 167, revenue: 678.40 },
    { item: affiliateItems[1], clicks: 1890, conversions: 145, revenue: 542.80 },
  ],
  payouts: [
    { id: "pay-1", user_id: "user-1", amount: 347.52, status: "completed", stripe_transfer_id: "tr_123", period_start: "2024-11-01", period_end: "2024-11-30", created_at: "2024-11-30T12:00:00Z" },
    { id: "pay-2", user_id: "user-1", amount: 412.80, status: "completed", stripe_transfer_id: "tr_456", period_start: "2024-10-01", period_end: "2024-10-31", created_at: "2024-10-31T12:00:00Z" },
    { id: "pay-3", user_id: "user-1", amount: 289.35, status: "completed", stripe_transfer_id: "tr_789", period_start: "2024-09-01", period_end: "2024-09-30", created_at: "2024-09-30T12:00:00Z" },
    { id: "pay-4", user_id: "user-1", amount: 523.40, status: "completed", stripe_transfer_id: "tr_012", period_start: "2024-08-01", period_end: "2024-08-31", created_at: "2024-08-31T12:00:00Z" },
  ],
};

export const mockStyleDNA: StyleDNA = {
  primary_style: "Minimalist Chic",
  color_palette: ["#1C1917", "#F5F5F4", "#BE185D", "#7C3AED", "#92400E", "#164E63"],
  favorite_brands: ["Zara", "COS", "Reformation", "AllSaints", "Everlane"],
  occasion_breakdown: [
    { occasion: "Casual", percentage: 35 },
    { occasion: "Work", percentage: 25 },
    { occasion: "Date Night", percentage: 15 },
    { occasion: "Formal", percentage: 10 },
    { occasion: "Athletic", percentage: 8 },
    { occasion: "Other", percentage: 7 },
  ],
  category_breakdown: [
    { category: "Tops", count: 45 },
    { category: "Bottoms", count: 32 },
    { category: "Dresses", count: 28 },
    { category: "Shoes", count: 24 },
    { category: "Outerwear", count: 18 },
    { category: "Bags", count: 15 },
    { category: "Accessories", count: 42 },
    { category: "Jewelry", count: 30 },
  ],
};
